server:
  port: 8083

kc:
  base-url: ${BASE_URL}
  realm: ${REALM}
  realm-url: ${kc.base-url}/realms/${kc.realm}
  user: ${KEYCLOAK_USER}
  password: ${KEYCLOAK_PASSWORD}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${kc.realm-url}
          jwk-set-uri: ${kc.realm-url}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid, profile
        provider:
          keycloak:
            issuer-uri: ${kc.realm-url}